// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjlvullrsgepsoqyeali.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqbHZ1bGxyc2dlcHNvcXllYWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzkyNzgsImV4cCI6MjA3MTcxNTI3OH0.3znjDsjFP93YOJOEkn-XpalCK17yPHXUxFSfbu22ZrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});